<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Amazon_Category_Validation_Excel</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>664fae07-9d0a-4822-914b-ead0e6069de4</testSuiteGuid>
   <testCaseLink>
      <guid>e92968d0-ea86-4b3d-84c9-1e99b831efbc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Amazon/TC_Validation Amazon Category_001</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>655b650b-f862-4e63-9757-acbe56048052</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Amazon_Category_Validation_Excel_Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>655b650b-f862-4e63-9757-acbe56048052</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>category</value>
         <variableId>68319a9f-9c80-465d-911a-efc39080febb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>655b650b-f862-4e63-9757-acbe56048052</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>item</value>
         <variableId>5bd28a7a-2bb2-4cd7-adb4-8e16783c164c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
